[package]
name = "rust-3d-demo"
version = "0.1.0"
authors = ["Dima Chernyshev"]
adition = "2022"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
lazy_static = "1.3.0"
nalgebra = "0.31.0"
wasm-bindgen = "0.2.44"

[dependencies.web-sys]
version = "0.3.57"
features = [
    'Document',
    'Element',
    'EventTarget',
    'HtmlCanvasElement',
    'MouseEvent',
    'WebGlBuffer',
    'WebGlProgram',
    'WebGlRenderingContext',
    'WebGlShader',
    'WebGlUniformLocation',
    'Window',
]